import '@/styles/globals.css'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import clsx from 'clsx'
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const montserrat = localFont({
  variable: '--font-montserrat',
  display: 'swap',
  fallback: ['sans-serif'],
  src: [
    {
      path: '../../public/fonts/Montserrat-regular.woff2',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Montserrat-italic.woff2',
      style: 'italic',
    },
  ],
})

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body className={clsx('relative h-screen', montserrat.variable)}>
        <main>{children}</main>
      </body>
    </html>
  )
}
